-- MySQL Script generated by MySQL Workbench
-- Tue May 14 21:04:55 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema artgalery
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema artgalery
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `artgalery` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`timestamps`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`timestamps` ;

CREATE TABLE IF NOT EXISTS `mydb`.`timestamps` (
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` TIMESTAMP NULL);


-- -----------------------------------------------------
-- Table `mydb`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`user` ;

CREATE TABLE IF NOT EXISTS `mydb`.`user` (
  `username` VARCHAR(16) NOT NULL,
  `email` VARCHAR(255) NULL,
  `password` VARCHAR(32) NOT NULL,
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP);


-- -----------------------------------------------------
-- Table `mydb`.`category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`category` ;

CREATE TABLE IF NOT EXISTS `mydb`.`category` (
  `category_id` INT NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`category_id`));


-- -----------------------------------------------------
-- Table `mydb`.`timestamps_1`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`timestamps_1` ;

CREATE TABLE IF NOT EXISTS `mydb`.`timestamps_1` (
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` TIMESTAMP NULL);

USE `artgalery` ;

-- -----------------------------------------------------
-- Table `artgalery`.`artist`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `artgalery`.`artist` ;

CREATE TABLE IF NOT EXISTS `artgalery`.`artist` (
  `artistId` INT NOT NULL,
  `firstName` VARCHAR(50) NULL DEFAULT NULL,
  `lastName` VARCHAR(50) NULL DEFAULT NULL,
  `interviewDate` DATE NULL DEFAULT NULL,
  `interviewerName` VARCHAR(50) NULL DEFAULT NULL,
  `areaCode` CHAR(3) NULL DEFAULT NULL,
  `telephoneNumber` CHAR(10) NULL DEFAULT NULL,
  `street` VARCHAR(100) NULL DEFAULT NULL,
  `zip` CHAR(5) NULL DEFAULT NULL,
  `salesLastYear` DECIMAL(10,2) NULL DEFAULT NULL,
  `salesYearToDate` DECIMAL(10,2) NULL DEFAULT NULL,
  `socialSecurityNumber` CHAR(11) NULL DEFAULT NULL,
  `usualMedium` VARCHAR(50) NULL DEFAULT NULL,
  `usualStyle` VARCHAR(50) NULL DEFAULT NULL,
  `usualType` VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`artistId`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `artgalery`.`artwork`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `artgalery`.`artwork` ;

CREATE TABLE IF NOT EXISTS `artgalery`.`artwork` (
  `artworkId` INT NOT NULL,
  `artistId` INT NULL DEFAULT NULL,
  `workTitle` VARCHAR(100) NULL DEFAULT NULL,
  `askingPrice` DECIMAL(10,2) NULL DEFAULT NULL,
  `dateListed` DATE NULL DEFAULT NULL,
  `dateReturned` DATE NULL DEFAULT NULL,
  `dateShown` DATE NULL DEFAULT NULL,
  `status` VARCHAR(20) NULL DEFAULT NULL,
  `workMedium` VARCHAR(50) NULL DEFAULT NULL,
  `workSize` VARCHAR(50) NULL DEFAULT NULL,
  `workStyle` VARCHAR(50) NULL DEFAULT NULL,
  `workType` VARCHAR(50) NULL DEFAULT NULL,
  `workYearCompleted` INT NULL DEFAULT NULL,
  `collectorSocialSecurityNumber` CHAR(11) NULL DEFAULT NULL,
  PRIMARY KEY (`artworkId`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `artgalery`.`collector`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `artgalery`.`collector` ;

CREATE TABLE IF NOT EXISTS `artgalery`.`collector` (
  `socialSecurityNumber` CHAR(11) NOT NULL,
  `firstName` VARCHAR(50) NULL DEFAULT NULL,
  `lastName` VARCHAR(50) NULL DEFAULT NULL,
  `street` VARCHAR(100) NULL DEFAULT NULL,
  `zip` CHAR(5) NULL DEFAULT NULL,
  `interviewDate` DATE NULL DEFAULT NULL,
  `interviewerName` VARCHAR(50) NULL DEFAULT NULL,
  `areaCode` CHAR(3) NULL DEFAULT NULL,
  `telephoneNumber` CHAR(10) NULL DEFAULT NULL,
  `salesLastYear` DECIMAL(10,2) NULL DEFAULT NULL,
  `salesYearToDate` DECIMAL(10,2) NULL DEFAULT NULL,
  `collectionArtistId` INT NULL DEFAULT NULL,
  `collectionMedium` VARCHAR(50) NULL DEFAULT NULL,
  `collectionStyle` VARCHAR(50) NULL DEFAULT NULL,
  `collectionType` VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`socialSecurityNumber`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `artgalery`.`potentialcustomer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `artgalery`.`potentialcustomer` ;

CREATE TABLE IF NOT EXISTS `artgalery`.`potentialcustomer` (
  `potentialCustomerId` INT NOT NULL,
  `firstName` VARCHAR(50) NULL DEFAULT NULL,
  `lastName` VARCHAR(50) NULL DEFAULT NULL,
  `areaCode` CHAR(3) NULL DEFAULT NULL,
  `telephoneNumber` CHAR(10) NULL DEFAULT NULL,
  `street` VARCHAR(100) NULL DEFAULT NULL,
  `zip` CHAR(5) NULL DEFAULT NULL,
  `dateFilledIn` DATE NULL DEFAULT NULL,
  `preferredArtistId` INT NULL DEFAULT NULL,
  `preferredMedium` VARCHAR(50) NULL DEFAULT NULL,
  `preferredStyle` VARCHAR(50) NULL DEFAULT NULL,
  `preferredType` VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`potentialCustomerId`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `artgalery`.`shoow`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `artgalery`.`shoow` ;

CREATE TABLE IF NOT EXISTS `artgalery`.`shoow` (
  `showTitle` VARCHAR(100) NOT NULL,
  `showFeaturedArtistId` INT NULL DEFAULT NULL,
  `showClosingDate` DATE NULL DEFAULT NULL,
  `showTheme` VARCHAR(100) NULL DEFAULT NULL,
  `showOpeningDate` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`showTitle`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `artgalery`.`shownin`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `artgalery`.`shownin` ;

CREATE TABLE IF NOT EXISTS `artgalery`.`shownin` (
  `artworkId` INT NOT NULL,
  `showTitle` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`artworkId`, `showTitle`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `artgalery`.`zips`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `artgalery`.`zips` ;

CREATE TABLE IF NOT EXISTS `artgalery`.`zips` (
  `zip` CHAR(5) NOT NULL,
  `city` VARCHAR(50) NULL DEFAULT NULL,
  `state` CHAR(2) NULL DEFAULT NULL,
  PRIMARY KEY (`zip`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
